apiVersion: v1

kind: Pod

metadata:
  name: webserver
  namespace: myapp
  labels:
    app : webserver

spec:
  serviceAccountName: my-app-service-account # Use a dedicated service account
  containers:
  - name: webserver
    image: docker.io/nginxinc/nginx-unprivileged@sha256:e4b1443de87899643f59ffc597a5caa81dfcb5af287c869d37cdb7db10a6a6d3
    imagePullPolicy: Always

    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10

    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10

    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 10001
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL

    resources:
      limits:
        cpu: "200m"
        memory: "20Mi"
      requests:
        cpu: "100m"
        memory: "10Mi"
    volumeMounts:
    - mountPath: /tmp
      name: tmp
  
  volumes:
  - emptyDir: {}
    name: tmp

  automountServiceAccountToken: false

  securityContext:
    seccompProfile:
      type: RuntimeDefault
