name: Code Check

on:
  push:
    paths:
      - '**/*.py'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8 --max-line-length=220 --extend-exclude=*.pyc,*__init__.py,./venv/*,./jasapp/rules/kubernetes/* ./

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run pytest for Kubernetes syntax rules
        run: pytest jasapp/rules/kubernetes/syntax/*.py

      - name: Run pytest for Kubernetes security rules
        run: pytest jasapp/rules/kubernetes/security/*.py

      - name: Run pytest for Kubernetes performance rules
        run: pytest jasapp/rules/kubernetes/performance/*.py

      - name: Run pytest for Dockerfile syntax rules
        run: pytest jasapp/rules/dockerfile/syntax/*.py

      - name: Run pytest for Dockerfile security rules
        run: pytest jasapp/rules/dockerfile/security/*.py

      - name: Run pytest for Dockerfile performance rules
        run: pytest jasapp/rules/dockerfile/performance/*.py