name: Docker Release

on:
  push:
    branches:
      - main

jobs:
  docker-release:
    runs-on: ubuntu-latest
    env:
      TEST_IMAGE: ${{ secrets.DOCKER_HUB_REGISTRY_USER }}/jasapp:${{ github.ref_name }}
      RELEASE_IMAGE: ${{ secrets.DOCKER_HUB_REGISTRY_USER }}/jasapp:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Pull test image
        run: docker pull ${{ env.TEST_IMAGE }}

      - name: Tag test image as release image
        run: docker tag ${{ env.TEST_IMAGE }} ${{ env.RELEASE_IMAGE }}

      - name: Push release image
        run: docker push ${{ env.RELEASE_IMAGE }}